name: Check
on: 
    push:
      branches:
        - main
    pull_request:
    # Sequence of patterns matched against refs/heads
      branches:
        - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      
